# Generated by Django 6.0 on 2025-12-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("tmdb_id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("release_date", models.CharField(blank=True, null=True)),
                ("vote_average", models.FloatField()),
                ("overview", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
