# Generated by Django 5.2.4 on 2025-12-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('name_kr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('tmdb_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.CharField(blank=True, null=True)),
                ('vote_average', models.FloatField()),
                ('overview', models.TextField(blank=True, null=True)),
                ('genres', models.CharField(default='[]', max_length=255)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('list_type', models.CharField(max_length=50)),
                ('backdrop_paths', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
