# Generated by Django 5.2.4 on 2025-12-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_paths',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
