# Generated by Django 6.0 on 2025-12-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="list_type",
            field=models.CharField(default="", max_length=50),
        ),
    ]
