# Generated by Django 5.2.4 on 2025-12-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_list_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("backdrop_image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=models.CharField(default="[]", max_length=255),
        ),
        migrations.AddField(
            model_name="movie",
            name="runtime",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="list_type",
            field=models.CharField(max_length=50),
        ),
    ]
