# Generated by Django 5.2.4 on 2025-12-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movieimage_movie_genres_movie_runtime_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MovieImage",
        ),
        migrations.AddField(
            model_name="movie",
            name="backdrop_paths",
            field=models.TextField(blank=True, null=True),
        ),
    ]
